// react-js/src/App.jsx
import React from 'react'

export default class App extends React.Component {
  render () {
    return (
      <div className={'root'}>
        <p>{this.state.text}</p>
        <button onClick={this.click}>click</button>
      </div>
    )
  }

  constructor (props) {
    super(props)
    this.state = {
      text: 'React JavaScript'
    }
    this.click = this.click.bind(this)
  }

  click () {
    this.setState((prevState) => {
      return {
        text: prevState.text + '!!!'
      }
    })
  }
}

(async function () {
  const ms = await (ms => new Promise(resolve => {
    setTimeout(() => {
      resolve(ms)
    }, ms)
  }))(1000)
  console.log(ms)
})()

// electron-vue-js/app/src/App.vue
<template>
<div class="root" id="root">
  <p>{{text}}</p>
  <button @click="text = text + '!!!'">click</button>
</div>
</template>

<script>
export default {
  data () {
    return {
      text: 'Vue JavaScript'
    }
  }
}

;(async function () {
  const ms = await (ms => new Promise(resolve => {
    setTimeout(() => {
      resolve(ms)
    }, ms)
  }))(1000)
  console.log(ms)
})()
</script>

<style scoped>
.root {
  background: #eee;
  color: #000;
}
</style>
