// react-ts/src/App.tsx
import * as React from 'react'

export default class App extends React.Component<{}, { text: string }> {
  render () {
    return (
      <div className={'root'}>
        <p>{this.state.text}</p>
        <button onClick={this.click}>click</button>
      </div>
    )
  }

  constructor (props: {}) {
    super(props)
    this.state = {
      text: 'React TypeScript'
    }
    this.click = this.click.bind(this)
  }

  click () {
    this.setState((prevState) => {
      return {
        text: prevState.text + '!!!'
      }
    })
  }
}

(async function () {
  const ms = await (ms => new Promise(resolve => {
    setTimeout(() => {
      resolve(ms)
    }, ms)
  }))(1000)
  console.log(ms)
})()

// vue-ts/src/App.vue
<template>
<div class="root" id="root">
  <p>{{text}}</p>
  <button @click="text = text + '!!!'">click</button>
</div>
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'

@Component
export default class extends Vue {
  text: string = 'Vue Typescript'
}

(async function () {
  const ms = await (ms => new Promise(resolve => {
    setTimeout(() => {
      resolve(ms)
    }, ms)
  }))(1000)
  console.log(ms)
})()
</script>

<style scoped>
.root {
  background: #eee;
  color: #000;
}
</style>
