// electron-react-js/src/renderer/App.jsx
import React from 'react'

class App extends React.Component {
  render () {
    return (
      <div className={'root'}>
        <img src="../../static.asar/128x128.png" />
        <h1 className="title">Electron React JavaScript</h1>
        <div>React: {React.version}</div>
        <div>Electron: {process.versions.electron}</div>
        <div className="content" onClick={this.test}>Component State: {this.state.count}</div>
      </div>
    )
  }

  constructor (props) {
    super(props)
    this.state = {
      count: 0
    }
    this.test = this.test.bind(this)
  }

  test () {
    this.setState((prevState) => {
      return {
        count: prevState.count + 1
      }
    })
  }
}

(async function () {
  const ms = await (ms => new Promise(resolve => {
    setTimeout(() => {
      resolve(ms)
    }, ms)
  }))(1000)
  console.log(ms)
})()

export default process.env.NODE_ENV !== 'production' ? require('react-hot-loader').hot(module)(App) : App

// electron-vue-ts/src/renderer/App.vue
<template>
<div class="root" id="root">
  <img :src="'../../static.asar/128x128.png'" />
  <h1 class="title">Electron Vue TypeScript</h1>
  <div>Vue: {{version}}</div>
  <div>Electron: {{electronVersion}}</div>
  <div class="content" @click="test">Component State: {{count}}</div>
</div>
</template>

<script lang="ts" src="./app.ts">
</script>

<style lang="stylus" scoped>
.root
  width 100%
  height 100%
  position absolute
  display flex
  flex-direction column
  justify-content center
  align-items center

.title
  color rgb(79, 192, 141)
  font-weight bold
  margin-bottom 20px

.content
  cursor pointer
</style>
